# The path for store your images, better be an absolute path
img_dir: /Users/liujin/Desktop/images

# Port for running image resolve process
resolve_server_port: 18000

# Port for running image uploader process
uploader_server_port: 18001

# Your AccessToken for upload images, generate by yourself
access_token: '000'

# Whether or not print log
log_enable: true

# Enable Image Resolver Server
resolver_enable: true

# Enable Image Uploader Server
uploader_enable: true

# Path of watermark image
watermark_path: './watermark.png'

# Add watermark after upload an image automatically
add_watermark: true

# Whether or not generate webp format image
generate_webp: true